/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenes.quimica.vista;

import examenes.quimica.db.CatalogosDAO;
import java.sql.Connection;

/**
 *
 * @author desarrollo
 */
public class ExamenesMain extends javax.swing.JFrame {

    private static final long serialVersionUID = -5922488092922618861L;
    
    private Connection connection;
    private final CatalogosDAO catalogosDAO;

    /**
     * Creates new form ExamenesMain
     */
    public ExamenesMain() {
        initComponents();
        catalogosDAO = new CatalogosDAO();
        this.connection = catalogosDAO.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuExamenes = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuPreguntas = new javax.swing.JMenu();
        menuPregAlta = new javax.swing.JMenuItem();
        mnuPregConsulta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXAMENES QUIMICA");
        setResizable(false);

        menuExamenes.setText("Catálogos");

        jMenuItem2.setText("Materias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirCatMaterias(evt);
            }
        });
        menuExamenes.add(jMenuItem2);

        jMenuBar1.add(menuExamenes);

        menuPreguntas.setText("Preguntas");

        menuPregAlta.setText("Registro");
        menuPregAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaPreguntas(evt);
            }
        });
        menuPreguntas.add(menuPregAlta);

        mnuPregConsulta.setText("Consulta");
        mnuPregConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPreguntas(evt);
            }
        });
        menuPreguntas.add(mnuPregConsulta);

        jMenuBar1.add(menuPreguntas);

        jMenu1.setText("Exámenes");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirNuevoExamen(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Consulta");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirConsultaExamen(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCatMaterias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirCatMaterias
        MateriasVista mv = new MateriasVista(connection);
        this.add(mv);
        mv.show();
    }//GEN-LAST:event_abrirCatMaterias

    private void altaPreguntas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaPreguntas
        PreguntasVista pv = new PreguntasVista(connection);
        this.add(pv);
        pv.show();
    }//GEN-LAST:event_altaPreguntas

    private void consultaPreguntas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPreguntas
        PreguntasConsultaVista pcv = new PreguntasConsultaVista(connection);
        this.add(pcv);
        pcv.show();
    }//GEN-LAST:event_consultaPreguntas

    private void abrirNuevoExamen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirNuevoExamen
        ExamenVista ev = new ExamenVista(connection);
        this.add(ev);
        ev.show();
    }//GEN-LAST:event_abrirNuevoExamen

    private void abrirConsultaExamen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirConsultaExamen
        ExamenesConsultaVista ecv = new ExamenesConsultaVista(connection);
        this.add(ecv);
        ecv.show();
    }//GEN-LAST:event_abrirConsultaExamen

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenesMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenesMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenesMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenesMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenesMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuExamenes;
    private javax.swing.JMenuItem menuPregAlta;
    private javax.swing.JMenu menuPreguntas;
    private javax.swing.JMenuItem mnuPregConsulta;
    // End of variables declaration//GEN-END:variables
}
