/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenes.quimica.vista;

import examenes.quimica.db.CatalogosDAO;
import examenes.quimica.db.ExamenesDAO;
import examenes.quimica.db.PreguntasDAO;
import examenes.quimica.excepciones.ExamenesQuimicaException;
import examenes.quimica.modelo.CatMateria;
import examenes.quimica.modelo.Examen;
import examenes.quimica.modelo.Pregunta;
import examenes.quimica.reportes.vo.ExamenReporteVO;
import examenes.quimica.util.ConstantesUtil;
import examenes.quimica.util.ReportesManager;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author desarrollo
 */
public class ExamenVista extends FormBase {

    private static final long serialVersionUID = 2241099364900823672L;
    
    private static final String ESPACIO = " ";
    private static final String TABULADOR = "\t";

    private final CatalogosDAO catalogosDAO;
    private final ExamenesDAO examenesDAO;
    private final PreguntasDAO preguntasDAO;
    private final ReportesManager reportesManager;
    private Examen examen;
    
    /**
     * Creates new form ExamenVista
     * @param con
     */
    public ExamenVista(Connection con) {
        initComponents();
        catalogosDAO = new CatalogosDAO(con);
        examenesDAO = new ExamenesDAO(con);
        preguntasDAO = new PreguntasDAO(con);
        lblEditando.setVisible(false);
        reportesManager = new ReportesManager(con);
        cargarCatalogos();
    }
    
    public ExamenVista(Connection con, int idExamen) {
        initComponents();
        catalogosDAO = new CatalogosDAO(con);
        examenesDAO = new ExamenesDAO(con);
        preguntasDAO = new PreguntasDAO(con);
        reportesManager = new ReportesManager(con);
        cargarCatalogos();
        lblEditando.setVisible(true);
        examen = examenesDAO.buscarPorId(idExamen);
        
        cboMateria.setSelectedItem(examen.getMateria().toString());
        cboMateria.setEnabled(false);
        cboUnidad.setSelectedIndex(examen.getUnidad());
        cboUnidad.setEnabled(false);
        txtNombre.setText(examen.getNombre());
        
        for (Pregunta p : examen.getPreguntas()) {
            ((DefaultTableModel) tblPreguntas.getModel()).addRow(new Object[]{p.getId(), p.getPregunta()});
        }
    }
    
    private void cargarCatalogos() {
        List<CatMateria> materias = catalogosDAO.buscarMateria(null);
        DefaultComboBoxModel modelMat = new DefaultComboBoxModel();
        modelMat.addElement("Seleccione");
        for (CatMateria m : materias) {
            modelMat.addElement(m.toString());
        }
        cboMateria.setModel(modelMat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboMateria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboUnidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboPregunta = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreguntas = new javax.swing.JTable();
        btnExportar = new javax.swing.JButton();
        lblEditando = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Exámenes");

        jLabel1.setText("Materia");

        cboMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPreguntas(evt);
            }
        });

        jLabel2.setText("Unidad");

        cboUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "ORD", "EXT", "TIT", "EXTIT" }));
        cboUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarPreguntasUnidad(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Pregunta");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPregunta(evt);
            }
        });

        tblPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Pregunta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPreguntas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitarPregunta(evt);
            }
        });
        jScrollPane1.setViewportView(tblPreguntas);
        if (tblPreguntas.getColumnModel().getColumnCount() > 0) {
            tblPreguntas.getColumnModel().getColumn(0).setPreferredWidth(80);
        }

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportar(evt);
            }
        });

        lblEditando.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblEditando.setForeground(new java.awt.Color(255, 0, 51));
        lblEditando.setText("E D I T A N D O . . .");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPregunta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEditando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnAgregar)
                    .addComponent(btnExportar)
                    .addComponent(lblEditando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarPreguntas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPreguntas
        cargarPreguntas();
    }//GEN-LAST:event_actualizarPreguntas

    private void cargarPreguntas() {
        cboPregunta.removeAllItems();
        if (cboMateria.getSelectedIndex() > 0 && cboUnidad.getSelectedIndex() > 0) {
            Pregunta filtro = new Pregunta();
            filtro.setUnidad(cboUnidad.getSelectedIndex());
            filtro.setMateria(new CatMateria(Integer.parseInt(cboMateria.getSelectedItem().toString().split(" - ")[0]), 
                    cboMateria.getSelectedItem().toString().split(" - ")[1]));
            List<Pregunta> preguntas = preguntasDAO.consultaPreguntas(filtro);
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model.addElement("Seleccione");
            for (Pregunta p : preguntas) {
                model.addElement(p.getId() + " - " + p.getPregunta());
            }
            cboPregunta.setModel(model);
        }
    }
    
    private void guardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar
        if (confirmarPregunta("Desea guardar el examen?")) {
            if (cboMateria.getSelectedIndex() == 0) {
                agregarMensajeAdvertencia("La Materia es requerida");
                return;
            }
            if (cboUnidad.getSelectedIndex() == 0) {
                agregarMensajeAdvertencia("La Unidad es requerida");
                return;
            }
            if (txtNombre.getText() == null || txtNombre.getText().isEmpty()) {
                agregarMensajeAdvertencia("El Nombre es requerido");
                return;
            }
            if (tblPreguntas.getRowCount() == 0) {
                agregarMensajeAdvertencia("Las preguntas son requeridas");
                return;
            }
            if (examen == null) {
                examen = new Examen();
            }
            examen.setMateria(new CatMateria(Integer.parseInt(cboMateria.getSelectedItem().toString().split(" - ")[0]), 
                    cboMateria.getSelectedItem().toString().split(" - ")[1]));
            examen.setUnidad(cboUnidad.getSelectedIndex());
            examen.setNombre(txtNombre.getText());

            List<Pregunta> preguntas = new ArrayList<>();
            for (int i = 0; i < tblPreguntas.getRowCount(); i++) {
                Pregunta p = new Pregunta();
                p.setId((Integer) tblPreguntas.getValueAt(i, 0));
                preguntas.add(p);
            }
            examen.setPreguntas(preguntas);
            try {
                if (examen.getId() == 0) {
                    examenesDAO.guardarExamen(examen);
                    agregarMensajeExito("El Examen se guardó correctamente");
                } else {
                    examenesDAO.actualizarExamen(examen);
                    agregarMensajeExito("El Examen se actualizó correctamente");
                }
                this.dispose();
            } catch (ExamenesQuimicaException ex) {
                agregarMensajeError(ex.getMessage());
            }
        }
    }//GEN-LAST:event_guardar

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        limpiarTabla(tblPreguntas);
        txtNombre.setText(null);
        cboPregunta.setSelectedIndex(0);
        if (examen == null || examen.getId() == 0) {
            cboMateria.setSelectedIndex(0);
            cboUnidad.setSelectedIndex(0);
        }
    }//GEN-LAST:event_limpiar

    private void agregarPregunta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPregunta
        if (cboPregunta.getSelectedIndex() > 0) {
            Pregunta p = new Pregunta();
            p.setId(Integer.parseInt(cboPregunta.getSelectedItem().toString().split(" - ")[0]));
            p.setPregunta(cboPregunta.getSelectedItem().toString().split(" - ")[1]);
            if (tblPreguntas.getRowCount() > 0) {
                for (int i = 0; i < tblPreguntas.getRowCount(); i++) {
                    if ((Integer) tblPreguntas.getValueAt(i, 0) == p.getId()) {
                        agregarMensajeAdvertencia("La pregunta ya fue agregada");
                        return;
                    }
                }
            }
            ((DefaultTableModel) tblPreguntas.getModel()).addRow(new Object[]{p.getId(), p.getPregunta()});
        } else {
            agregarMensajeAdvertencia("Debe seleccionar la pregunta");
        }
    }//GEN-LAST:event_agregarPregunta

    private void exportar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportar
        if (cboMateria.getSelectedIndex() == 0) {
            agregarMensajeAdvertencia("La Materia es requerida");
            return;
        }
        if (cboUnidad.getSelectedIndex() == 0) {
            agregarMensajeAdvertencia("La Unidad es requerida");
            return;
        }
        if (tblPreguntas.getRowCount() == 0) {
            agregarMensajeAdvertencia("No se han especificado las preguntas del reporte");
            return;
        }
        List<ExamenReporteVO> preguntas = new ArrayList<>();
        for (int i = 0; i < tblPreguntas.getRowCount(); i++) {
            Pregunta p = preguntasDAO.consultaPreguntaId((Integer) tblPreguntas.getValueAt(i, 0));
            List<Map<String,String>> respuesta = new ArrayList<>();
            ExamenReporteVO ervo = new ExamenReporteVO();
            ervo.setPregunta((i + 1) + ". " + p.getPregunta());
            int linea = 0;
            switch (p.getTipoRespuesta().getId()) {
                case ConstantesUtil.RESPUESTA_ABIERTA:
                case ConstantesUtil.RESPUESTA_MAPA:
                    int numRen = Integer.parseInt(p.getOpciones().split(";")[0]);
                    Map<String, String> mapa = new HashMap<>();
                    for (int nr = 0; nr < numRen; nr++) {
                        mapa.put("campo1", ESPACIO);
                        respuesta.add(mapa);
                    }
                    break;
                case ConstantesUtil.RESPUESTA_OPCION:
                    respuesta.add(generarMapa(p.getOpciones().split(";"), ervo));
                    break;
                case ConstantesUtil.RESPUESTA_TABLA:
                    linea = 1;
                    String[] renglones = p.getOpciones().split("#");
                    String[] encabezados = renglones[0].split(";");
                    respuesta.add(generarMapa(encabezados, ervo));
                    for (int rr = 1; rr < renglones.length; rr++) {
                        respuesta.add(generarMapa(renglones[rr].split(";"), ervo));
                    }
            }
            
            ervo.setRespuesta(respuesta);
            ervo.setLinea(linea);
            preguntas.add(ervo);
        }
        try {
            reportesManager.generarExamen(cboMateria.getSelectedItem().toString().split(" - ")[1], 
                    txtNombre.getText(), preguntas);
        } catch(ExamenesQuimicaException ex) {
            agregarMensajeError(ex.getMessage());
        }
    }//GEN-LAST:event_exportar

    private Map<String, String> generarMapa(String[] datos, ExamenReporteVO ervo) {
        Map<String, String> mapa = new HashMap<>();
        int cc = 1;
        int index = 1;
        if (datos.length <= 5) {
            cc = 10 / datos.length;
        }
        for (String d : datos) {
            mapa.put("campo" + index, d);
            switch (index) {
                case 1:
                    ervo.setLnCampo1(1);
                    break;
                case 2:
                    ervo.setLnCampo2(1);
                    break;
                case 3:
                    ervo.setLnCampo3(1);
                    break;
                case 4:
                    ervo.setLnCampo4(1);
                    break;
                case 5:
                    ervo.setLnCampo5(1);
                    break;
                case 6:
                    ervo.setLnCampo6(1);
                    break;
                case 7:
                    ervo.setLnCampo7(1);
                    break;
                case 8:
                    ervo.setLnCampo8(1);
                    break;
                case 9:
                    ervo.setLnCampo9(1);
                    break;
                case 10:
                    ervo.setLnCampo10(1);
                    break;
            }
            index += cc;
        }
        return mapa;
    }
    private void quitarPregunta(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitarPregunta
        if (confirmarPregunta(evt, "Desea quitar la pregunta?")) {
            ((DefaultTableModel) tblPreguntas.getModel()).removeRow(tblPreguntas.getSelectedRow());
        }
    }//GEN-LAST:event_quitarPregunta

    private void actualizarPreguntasUnidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarPreguntasUnidad
        cargarPreguntas();
    }//GEN-LAST:event_actualizarPreguntasUnidad


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboMateria;
    private javax.swing.JComboBox<String> cboPregunta;
    private javax.swing.JComboBox<String> cboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditando;
    private javax.swing.JTable tblPreguntas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
