/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenes.quimica.vista;

import examenes.quimica.db.CatalogosDAO;
import examenes.quimica.db.ExamenesDAO;
import examenes.quimica.modelo.CatMateria;
import examenes.quimica.modelo.Examen;
import java.sql.Connection;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author desarrollo
 */
public class ExamenesConsultaVista extends FormBase {

    private static final long serialVersionUID = -8609324274656834370L;
    
    private final CatalogosDAO catalogosDAO;
    private final ExamenesDAO examenesDAO;

    /**
     * Creates new form ExamenesConsultaVista
     * @param con
     */
    public ExamenesConsultaVista(Connection con) {
        initComponents();
        catalogosDAO = new CatalogosDAO(con);
        examenesDAO = new ExamenesDAO(con);
        
        List<CatMateria> materias = catalogosDAO.buscarMateria(null);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Seleccione");
        for (CatMateria m : materias) {
            model.addElement(m.toString());
        }
        cboMateria.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboMateria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboUnidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExamenes = new javax.swing.JTable();

        setClosable(true);
        setTitle("Consulta Examenes");
        setPreferredSize(new java.awt.Dimension(710, 363));

        jLabel1.setText("Materia");

        jLabel2.setText("Unidad");

        cboUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "ORD", "EXT", "TIT", "EXTIT" }));

        jLabel3.setText("Nombre");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarExamenes(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        tblExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Materia", "Unidad", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExamenes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargarExamen(evt);
            }
        });
        jScrollPane1.setViewportView(tblExamenes);
        if (tblExamenes.getColumnModel().getColumnCount() > 0) {
            tblExamenes.getColumnModel().getColumn(0).setResizable(false);
            tblExamenes.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblExamenes.getColumnModel().getColumn(1).setResizable(false);
            tblExamenes.getColumnModel().getColumn(1).setPreferredWidth(300);
            tblExamenes.getColumnModel().getColumn(2).setResizable(false);
            tblExamenes.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblExamenes.getColumnModel().getColumn(3).setResizable(false);
            tblExamenes.getColumnModel().getColumn(3).setPreferredWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarExamenes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarExamenes
        List<Examen> examenes = examenesDAO.buscarExamen(cboMateria.getSelectedIndex() > 0 ? Integer.parseInt(cboMateria.getSelectedItem().toString().split(" - ")[0]) : 0, 
                cboUnidad.getSelectedIndex(), txtNombre.getText());
        limpiarTabla(tblExamenes);
        if (examenes != null && !examenes.isEmpty()) {
            for (Examen e : examenes) {
                ((DefaultTableModel) tblExamenes.getModel()).addRow(new Object[]{e.getId(), e.getMateria().getNombre(), e.getUnidad(), e.getNombre()});
            }
        } else {
            agregarMensajeAdvertencia("No se encontraron resultados");
        }
    }//GEN-LAST:event_buscarExamenes

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        cboMateria.setSelectedIndex(0);
        cboUnidad.setSelectedIndex(0);
        txtNombre.setText(null);
        limpiarTabla(tblExamenes);
    }//GEN-LAST:event_limpiar

    private void cargarExamen(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargarExamen
        if (confirmarPregunta(evt, "Desea abrir el detalle del examen?")) {
            ExamenVista ev = new ExamenVista(catalogosDAO.getConnection(), Integer.parseInt(tblExamenes.getValueAt(tblExamenes.getSelectedRow(), 0).toString()));
            this.getParent().add(ev);
            this.dispose();
            ev.show();
        }
    }//GEN-LAST:event_cargarExamen


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboMateria;
    private javax.swing.JComboBox<String> cboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExamenes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
