/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenes.quimica.vista;

import examenes.quimica.db.CatalogosDAO;
import examenes.quimica.db.PreguntasDAO;
import examenes.quimica.modelo.CatMateria;
import examenes.quimica.modelo.CatRespuesta;
import examenes.quimica.modelo.Pregunta;
import java.sql.Connection;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author desarrollo
 */
public class PreguntasConsultaVista extends FormBase {

    private static final long serialVersionUID = 2763949942145380305L;

    private final CatalogosDAO catalogosDAO;
    private final PreguntasDAO preguntasDAO;
    private final Connection con;
    /**
     * Creates new form PreguntasConsultaVista
     * @param con
     */
    public PreguntasConsultaVista(Connection con) {
        initComponents();
        this.con = con;
        catalogosDAO = new CatalogosDAO(con);
        preguntasDAO = new PreguntasDAO(con);
        
        List<CatMateria> materias = catalogosDAO.buscarMateria(null);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (CatMateria m : materias) {
            model.addElement(m.toString());
        }
        cboMateria.setModel(model);
        
        List<CatRespuesta> respuestas = catalogosDAO.buscarRespuesta(null);
        DefaultComboBoxModel modelRes = new DefaultComboBoxModel();
        for (CatRespuesta res : respuestas) {
            modelRes.addElement(res.toString());
        }
        cboRespuesta.setModel(modelRes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboMateria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboUnidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboRespuesta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPregunta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPreguntas = new javax.swing.JTable();

        setClosable(true);
        setTitle("Consulta Preguntas");

        jLabel1.setText("Materia");

        jLabel2.setText("Unidad");

        cboUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4" }));

        jLabel3.setText("Tipo Respuesta");

        jLabel4.setText("Pregunta");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar(evt);
            }
        });

        tblPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Materia", "Unidad", "Pregunta", "Tipo Respuesta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPreguntas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblPreguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirDetalle(evt);
            }
        });
        jScrollPane1.setViewportView(tblPreguntas);
        if (tblPreguntas.getColumnModel().getColumnCount() > 0) {
            tblPreguntas.getColumnModel().getColumn(0).setResizable(false);
            tblPreguntas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblPreguntas.getColumnModel().getColumn(1).setResizable(false);
            tblPreguntas.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblPreguntas.getColumnModel().getColumn(2).setResizable(false);
            tblPreguntas.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblPreguntas.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblPreguntas.getColumnModel().getColumn(4).setResizable(false);
            tblPreguntas.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cboRespuesta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtPregunta))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addGap(12, 12, 12))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar
        limpiarTabla(tblPreguntas);
        Pregunta filtros = new Pregunta();
        if (cboMateria.getSelectedIndex() > 0) {
            filtros.getMateria().setId(Integer.parseInt(cboMateria.getSelectedItem().toString().split(" - ")[0]));
        }
        if (cboUnidad.getSelectedIndex() > 0) {
            filtros.setUnidad(cboUnidad.getSelectedIndex());
        }
        if (cboRespuesta.getSelectedIndex() > 0) {
            filtros.getTipoRespuesta().setId(Integer.parseInt(cboRespuesta.getSelectedItem().toString().split(" - ")[0]));
        }
        if (txtPregunta.getText() != null && !txtPregunta.getText().isEmpty()) {
            filtros.setPregunta(txtPregunta.getText());
        }
        List<Pregunta> preguntas = preguntasDAO.consultaPreguntas(filtros);
        if (preguntas == null || preguntas.isEmpty()) {
            agregarMensajeAdvertencia("No se encontraron resultados");
            return;
        }
        for (Pregunta p : preguntas) {
            ((DefaultTableModel) tblPreguntas.getModel()).addRow(new Object[]{p.getId(), p.getMateria().getNombre(), p.getUnidad(), p.getPregunta(), p.getTipoRespuesta().getNombre()});
        }
    }//GEN-LAST:event_buscar

    private void limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar
        limpiarTabla(tblPreguntas);
        cboMateria.setSelectedIndex(0);
        cboUnidad.setSelectedIndex(0);
        cboRespuesta.setSelectedIndex(0);
        txtPregunta.setText(null);
    }//GEN-LAST:event_limpiar

    private void abrirDetalle(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirDetalle
        if (confirmarPregunta(evt, "Desea editar la pregunta?")) {
            PreguntasVista pv = new PreguntasVista(con, (Integer) tblPreguntas.getValueAt(tblPreguntas.getSelectedRow(), 0));
            this.getParent().add(pv);
            pv.show();
            this.dispose();
        }
    }//GEN-LAST:event_abrirDetalle


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cboMateria;
    private javax.swing.JComboBox<String> cboRespuesta;
    private javax.swing.JComboBox<String> cboUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPreguntas;
    private javax.swing.JTextField txtPregunta;
    // End of variables declaration//GEN-END:variables
}
